// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7vYid4NQGnDqEB5ie3mjuWAqVqoxr8r4',
    appId: '1:1096766603001:web:a8d17fdd7a1eaea9906c28',
    messagingSenderId: '1096766603001',
    projectId: 'curdfirebaseflutter-30f26',
    authDomain: 'curdfirebaseflutter-30f26.firebaseapp.com',
    storageBucket: 'curdfirebaseflutter-30f26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkRhmAD21sU22tFy29dsa9412J6ys7vM',
    appId: '1:1096766603001:android:c0693565cd4db489906c28',
    messagingSenderId: '1096766603001',
    projectId: 'curdfirebaseflutter-30f26',
    storageBucket: 'curdfirebaseflutter-30f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3eWG6qJ4GPEac6qPRaBAvvGNWuAEimM',
    appId: '1:1096766603001:ios:0be3353d2a4fea9b906c28',
    messagingSenderId: '1096766603001',
    projectId: 'curdfirebaseflutter-30f26',
    storageBucket: 'curdfirebaseflutter-30f26.appspot.com',
    iosClientId: '1096766603001-n4h1r10hmo0bfnun9u4j1sbgvti79esa.apps.googleusercontent.com',
    iosBundleId: 'com.example.curdFirebaseFlutter',
  );
}
